[project]
name = "rag"
version = "0.1.0"
description = "RAG (Retrieval Augmented Generation) CLI"
authors = [
    { name = "Sam Quigley", email = "quigley@emerose.com" },
]
dependencies = [
    "langchain>=0.1.0",
    "langchain-community>=0.0.10",
    "langchain-openai>=0.0.5",
    "langchain-unstructured>=0.0.1",
    "langchain_core>=0.1.0",
    "langchain_text_splitters>=0.0.1",
    "faiss-cpu>=1.7.4",
    "unstructured[all-docs]>=0.10.0",
    "unstructured[local-inference]>=0.10.0",
    "unstructured[pdf]>=0.10.0",
    "unstructured[docx]>=0.10.0",
    "unstructured[pptx]>=0.10.0",
    "unstructured[xlsx]>=0.10.0",
    "unstructured[csv]>=0.10.0",
    "unstructured[md]>=0.10.0",
    "unstructured[rtf]>=0.10.0",
    "unstructured[odt]>=0.10.0",
    "unstructured[epub]>=0.10.0",
    "python-magic>=0.4.27",
    "docx2txt>=0.8",
    "tqdm>=4.66.0",
    "colorama>=0.4.6",
    "python-dotenv>=1.0.0",
    "typer>=0.9.0",
    "rich>=13.7.0",
    "textual>=0.47.1",
    "prompt_toolkit>=3.0.43",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }

[project.scripts]
rag = "rag.cli:run_cli"

[project.optional-dependencies]
dev = [
    "ruff>=0.3.0",
    "pre-commit>=3.6.0",
    "pytest>=8.3.0",
    "pytest-cov>=6.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
# Enable pycodestyle (`E`), Pyflakes (`F`), and import sorting (`I`) codes
select = ["E", "F", "B", "I", "N", "UP", "PL", "RUF"]
ignore = []

# Allow autofix for all enabled rules (when `--fix` is used)
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 88

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10
target-version = "py310"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.isort]
known-first-party = ["rag"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.per-file-ignores]
"tests/*" = ["PLR2004"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=rag --cov-report=term-missing"

[tool.setuptools]
packages = ["rag"]
package-dir = {"" = "src"}

[tool.hatch.build.targets.wheel]
packages = ["src/rag"]
