[tool.vulture]
# Paths to scan for dead code
paths = ["src/rag"]

# Minimum confidence level to report (default: 80)
# Set to 90 to focus only on high-confidence dead code
min_confidence = 90

# Only ignore items that are definitely used by frameworks but not visible to static analysis
ignore_names = [
    # Protocol method parameters (not used in protocol definitions with ...)
    "chunk_hashes",
    # Unused but required parameters in fake implementations
    "run_manager",  # Required by LangChain base class interface
    "mime_type",    # Required by text splitter interface but not used in fake implementation
]