"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum
from typing import AbstractSet, Any, Callable, Collection, Iterable, List, Literal, Optional, Sequence, Type, TypeVar, Union
from langchain_core.documents import BaseDocumentTransformer, Document

logger = ...
TS = TypeVar("TS", bound="TextSplitter")
class TextSplitter(BaseDocumentTransformer, ABC):
    """Interface for splitting text into chunks."""
    def __init__(self, chunk_size: int = ..., chunk_overlap: int = ..., length_function: Callable[[str], int] = ..., keep_separator: Union[bool, Literal["start", "end"]] = ..., add_start_index: bool = ..., strip_whitespace: bool = ...) -> None:
        """Create a new TextSplitter.

        Args:
            chunk_size: Maximum size of chunks to return
            chunk_overlap: Overlap in characters between chunks
            length_function: Function that measures the length of given chunks
            keep_separator: Whether to keep the separator and where to place it
                            in each corresponding chunk (True='start')
            add_start_index: If `True`, includes chunk's start index in metadata
            strip_whitespace: If `True`, strips whitespace from the start and end of
                              every document
        """
        ...
    
    @abstractmethod
    def split_text(self, text: str) -> List[str]:
        """Split text into multiple components."""
        ...
    
    def create_documents(self, texts: List[str], metadatas: Optional[List[dict]] = ...) -> List[Document]:
        """Create documents from a list of texts."""
        ...
    
    def split_documents(self, documents: Iterable[Document]) -> List[Document]:
        """Split documents."""
        ...
    
    @classmethod
    def from_huggingface_tokenizer(cls, tokenizer: Any, **kwargs: Any) -> TextSplitter:
        """Text splitter that uses HuggingFace tokenizer to count length."""
        ...
    
    @classmethod
    def from_tiktoken_encoder(cls: Type[TS], encoding_name: str = ..., model_name: Optional[str] = ..., allowed_special: Union[Literal["all"], AbstractSet[str]] = ..., disallowed_special: Union[Literal["all"], Collection[str]] = ..., **kwargs: Any) -> TS:
        """Text splitter that uses tiktoken encoder to count length."""
        ...
    
    def transform_documents(self, documents: Sequence[Document], **kwargs: Any) -> Sequence[Document]:
        """Transform sequence of documents by splitting them."""
        ...
    


class TokenTextSplitter(TextSplitter):
    """Splitting text to tokens using model tokenizer."""
    def __init__(self, encoding_name: str = ..., model_name: Optional[str] = ..., allowed_special: Union[Literal["all"], AbstractSet[str]] = ..., disallowed_special: Union[Literal["all"], Collection[str]] = ..., **kwargs: Any) -> None:
        """Create a new TextSplitter."""
        ...
    
    def split_text(self, text: str) -> List[str]:
        """Splits the input text into smaller chunks based on tokenization.

        This method uses a custom tokenizer configuration to encode the input text
        into tokens, processes the tokens in chunks of a specified size with overlap,
        and decodes them back into text chunks. The splitting is performed using the
        `split_text_on_tokens` function.

        Args:
            text (str): The input text to be split into smaller chunks.

        Returns:
            List[str]: A list of text chunks, where each chunk is derived from a portion
            of the input text based on the tokenization and chunking rules.
        """
        ...
    


class Language(str, Enum):
    """Enum of the programming languages."""
    CPP = ...
    GO = ...
    JAVA = ...
    KOTLIN = ...
    JS = ...
    TS = ...
    PHP = ...
    PROTO = ...
    PYTHON = ...
    RST = ...
    RUBY = ...
    RUST = ...
    SCALA = ...
    SWIFT = ...
    MARKDOWN = ...
    LATEX = ...
    HTML = ...
    SOL = ...
    CSHARP = ...
    COBOL = ...
    C = ...
    LUA = ...
    PERL = ...
    HASKELL = ...
    ELIXIR = ...
    POWERSHELL = ...


@dataclass(frozen=True)
class Tokenizer:
    """Tokenizer data class."""
    chunk_overlap: int
    tokens_per_chunk: int
    decode: Callable[[List[int]], str]
    encode: Callable[[str], List[int]]
    ...


def split_text_on_tokens(*, text: str, tokenizer: Tokenizer) -> List[str]:
    """Split incoming text and return chunks using tokenizer."""
    ...

