"""
This type stub file was generated by pyright.
"""

from typing import Any

from langchain_text_splitters.base import TextSplitter

class KonlpyTextSplitter(TextSplitter):
    """Splitting text using Konlpy package.

    It is good for splitting Korean text.
    """
    def __init__(self, separator: str = ..., **kwargs: Any) -> None:
        """Initialize the Konlpy text splitter."""
        ...

    def split_text(self, text: str) -> list[str]:
        """Split incoming text and return chunks."""
        ...
