"""
This type stub file was generated by pyright.
"""

from typing import Any

from langchain_text_splitters.character import RecursiveCharacterTextSplitter

class LatexTextSplitter(RecursiveCharacterTextSplitter):
    """Attempts to split the text along Latex-formatted layout elements."""
    def __init__(self, **kwargs: Any) -> None:
        """Initialize a LatexTextSplitter."""
        ...
