"""
This type stub file was generated by pyright.
"""

from typing import Any, List
from langchain_text_splitters.base import TextSplitter

class NLTKTextSplitter(TextSplitter):
    """Splitting text using NLTK package."""
    def __init__(self, separator: str = ..., language: str = ..., *, use_span_tokenize: bool = ..., **kwargs: Any) -> None:
        """Initialize the NLTK splitter."""
        ...
    
    def split_text(self, text: str) -> List[str]:
        """Split incoming text and return chunks."""
        ...
    


