"""
This type stub file was generated by pyright.
"""

from typing import Any

from langchain_text_splitters.character import RecursiveCharacterTextSplitter

class PythonCodeTextSplitter(RecursiveCharacterTextSplitter):
    """Attempts to split the text along Python syntax."""
    def __init__(self, **kwargs: Any) -> None:
        """Initialize a PythonCodeTextSplitter."""
        ...
