"""
This type stub file was generated by pyright.
"""

from typing import Any, List
from langchain_text_splitters.base import TextSplitter

class SpacyTextSplitter(TextSplitter):
    """Splitting text using Spacy package.

    Per default, Spacy's `en_core_web_sm` model is used and
    its default max_length is 1000000 (it is the length of maximum character
    this model takes which can be increased for large files). For a faster, but
    potentially less accurate splitting, you can use `pipeline='sentencizer'`.
    """
    def __init__(self, separator: str = ..., pipeline: str = ..., max_length: int = ..., *, strip_whitespace: bool = ..., **kwargs: Any) -> None:
        """Initialize the spacy text splitter."""
        ...
    
    def split_text(self, text: str) -> List[str]:
        """Split incoming text and return chunks."""
        ...
    


