"""
This type stub file was generated by pyright.
"""

from typing import Any

from langchain_core.embeddings import Embeddings
from langchain_core.messages import BaseMessage

"""Type stubs for langchain_openai package."""

class OpenAIEmbeddings(Embeddings):
    """OpenAI embeddings."""

    model: str
    openai_api_key: str | None
    def __init__(
        self, model: str = ..., openai_api_key: str | None = ..., **kwargs: Any
    ) -> None: ...
    def embed_documents(self, texts: list[str]) -> list[list[float]]: ...
    def embed_query(self, text: str) -> list[float]: ...

class ChatOpenAI:
    """OpenAI chat model."""

    model_name: str
    temperature: float
    openai_api_key: str | None
    def __init__(
        self,
        model_name: str = ...,
        temperature: float = ...,
        openai_api_key: str | None = ...,
        **kwargs: Any,
    ) -> None: ...
    def invoke(self, messages: list[BaseMessage], **kwargs: Any) -> BaseMessage: ...
    def __call__(self, messages: list[BaseMessage], **kwargs: Any) -> BaseMessage: ...
