"""
This type stub file was generated by pyright.
"""

from typing import Any

"""Type stubs for langchain_core.messages module."""

class BaseMessage:
    """Base class for messages."""

    content: str
    additional_kwargs: dict[str, Any]
    def __init__(
        self,
        content: str,
        additional_kwargs: dict[str, Any] | None = ...,
        **kwargs: Any,
    ) -> None: ...

class HumanMessage(BaseMessage):
    """A message from a human."""

    ...

class AIMessage(BaseMessage):
    """A message from an AI."""

    ...

class SystemMessage(BaseMessage):
    """A system message."""

    ...
