name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Create virtualenv
        run: uv venv .venv

      - name: Install dependencies
        run: |
          . .venv/bin/activate
          uv pip install -e .[dev]

      - name: Run unit tests
        run: python scripts/run_tests.py unit

      - name: Run integration tests
        run: python scripts/run_tests.py integration

      - name: Run formatter
        run: ruff format src/ --line-length 88
        
      - name: Run linter
        run: ruff check src/rag --line-length 88
