name: Integration Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Create virtualenv
        run: python -m venv .venv

      - name: Install dependencies
        run: |
          . .venv/bin/activate
          uv pip install -e .[dev]

      - name: Run integration tests
        run: python tests/run_integration_tests.py --verbose
